"""
Django settings for plant_keeper project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""
import os
from pathlib import Path

# 📁 Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# ⚙️ Security
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'some-default-secret-key-for-dev')
#DEBUG = os.environ.get('DEBUG', 'False') == 'True'
#ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
# 🧩 Installed apps
INSTALLED_APPS = [
    "main_app",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# 🧱 Middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",  # ✅ لازم موجود
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 🌿 URL & WSGI
ROOT_URLCONF = "plant_keeper.urls"
WSGI_APPLICATION = "plant_keeper.wsgi.application"

# 🧭 Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# 🗃 Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# 🔐 Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# 🌍 Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# 🎨 Static files (CSS, JS)
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "main_app" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# 🖼️ Media files (Uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# 🌱 Auth redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "plant_list"
LOGOUT_REDIRECT_URL = "login"

# 🆔 Default PK
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000", "http://localhost:8000"]
