# Generated by Django 5.2.7 on 2025-10-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carelog',
            old_name='action_type',
            new_name='action',
        ),
    ]
