# Generated by Django 5.2.7 on 2025-10-11 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_action_type_carelog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.CharField(default='Time to take care of your plant! 💧', max_length=255),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('Water', 'Water'), ('Fertilizer', 'Fertilizer'), ('Check Soil', 'Check Soil')], default='Water', max_length=50),
        ),
    ]
