# Generated by Django 5.2.7 on 2025-10-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='watering_frequency',
            field=models.IntegerField(default=7, help_text='Days between watering'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics', verbose_name='Your profile picture'),
        ),
    ]
